### ISSUE TITLE
Release 2.0.0.0 not installable

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#10]
The only release available in the winget CLI is still 1.3.0.1 and there is not MSI on the 2.0.0.0 release page.

**Comment by ghost1372** [comment]
I am working on version 2.1
After that, MSI will be added in Winget

**Comment by tardis4500** [comment]
I also notice if I download and unpack the rar from 2.0.0.0, the exe doesn't run but exits immediately. Is that release just broken?

**Comment by ghost1372** [comment]
> I also notice if I download and unpack the rar from 2.0.0.0, the exe doesn't run but exits immediately. Is that release just broken?

This problem is due to the libgit2sharp library, which I removed in version 2.1
There should be a PDB file next to the exe file,  This file is required to run (So make sure the file is available)
Anyway, I fixed this problem in version 2.1

**Comment by ghost1372** [comment]
@tardis4500 
you can try version 2.1
https://github.com/HandyOrg/HandyWinGet/releases/tag/v2.1.0.0
