### ISSUE TITLE
Installed packages not showing

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#11]
No matter which "Show Installed Package" method I choose in settings, the installed packages are never checked.

**Comment by ghost1372** [comment]
you need a refresh after selecting methods
![8](https://user-images.githubusercontent.com/9213496/104277743-a001f600-54bc-11eb-933f-8ccd7e9f2790.gif)

**Comment by tardis4500** [comment]
I did that. I installed putty, refreshed, and tried both methods but it never shows as installed.

**Comment by ghost1372** [comment]
I'm not sure, but i think putty probably won't create a registry key For this reason it is not identified in the list.

**Comment by tardis4500** [comment]
Even this HandyWinGet GUI doesn't show as installed.

**Comment by ghost1372** [comment]
The method we use to identify installed programs is to use registry keys Therefore, if an application does not have a registry key, it cannot be identified.
You can check the registry keys at this address **LocalMachine** and **CurrentUser**
```
"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
```

**Comment by JohnLGalt** [comment]
Any chance on adding additional verification methods?  

HW supports installing 7-Zip alpha 21.01-alpha, which I've already got installed directly from the 7-zip website, but it also doesn't show for the same  reason.

I suspect that installing it through HW would still yield it showing as not installed....
