### ISSUE TITLE
Settings aren't saved

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#12]
Every time I open the app, any settings I have selected are back to their defaults. This includes Pane Display Mode and Show Installed Package.

**Comment by ghost1372** [comment]
> Every time I open the app, any settings I have selected are back to their defaults. This includes Pane Display Mode and Show Installed Package.

Please delete the settings file (AppConfig.json) once and run the program again. There may be some settings from previous versions that are not in the new version and may cause interference.

**Comment by tardis4500** [comment]
That worked for everything but the theme. I set it to dark but it comes up light on the next launch.

**Comment by ghost1372** [comment]
I will try to check soon
Thanks for the report

**Comment by ghost1372** [comment]
@tardis4500  check new version
https://github.com/HandyOrg/HandyWinGet/releases/tag/v2.2.0.0

**Comment by tardis4500** [comment]
It's gotten worse. None of the settings are save now even after deleting the AppConfig.json.

**Comment by ghost1372** [comment]
@tardis4500 
In the reports section I see an access error
If you run the program from this location you need to run the program with administrator access
![Untitled](https://user-images.githubusercontent.com/9213496/108726295-7d8fdd80-753c-11eb-92cc-3bca53b61d14.png)

**Comment by tardis4500** [comment]
Running as Administrator didn't help.

**Comment by ghost1372** [comment]
it is strange, the settings are stored on my system without any problems
Please download and run [this version](https://github.com/HandyOrg/HandyWinGet/releases/download/test/HandyWinGet.rar), change the settings. If there is a problem, a file named **log.txt** should be created on your **desktop**.
Send me that file so I can identify the problem

**Comment by ghost1372** [comment]
@tardis4500  try new version 3.0.0.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.0.0.0
