### ISSUE TITLE
Latest version not always reported correctly.

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#13]
Looking at pgAdmin4, the latest version in the available versions list is 4.3.0.0 but in the "Latest Version" column it says the latest version is 4.29.0.0.

**Comment by ghost1372** [comment]
The program sorts the versions in ascending order
Since the version number is registered as 2 digits (x.29.x.x) and the next version is 1 digit (x.3.x.x), it causes interference
I hope I can solve this problem

**Comment by tardis4500** [comment]
That is not what I am seeing. The version in the drop down is 4.30.0.0 followed by 4.29.0.0. I have attached a screen shot showing they are sorted correctly in the versions list.
![Capture](https://user-images.githubusercontent.com/6739064/108857675-54f9f900-75b9-11eb-9abe-1b26c3343d40.PNG)

**Comment by ghost1372** [comment]
@tardis4500  oh you right,
I will try to solve this problem soon

**Comment by ghost1372** [comment]
@tardis4500 try new version 3.0.0.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.0.0.0
