### ISSUE TITLE
Unable to upgrade from within the app

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#15]
I'm running 2.2.0.0. When I click "Check For Update" I get the popup for the new version. If I select "Confirm" the app just closes. This happens whether I run as Administrator or not. I had the same problem upgrading from 2.0.0.0 to 2.2.0.0. I had to download the installer from the website.

**Comment by ghost1372** [comment]
I notice the issues in the previous versions, so I decided to re-create the program (v3.0.0)
The updater app was very simple and weak and I did not have enough time to improve it so I removed the internal updater app in version 3 and From now, if you click on check for update, if there is a new version, the download page will open in the browser
In the future, if I have enough time, I will try to create a better updater😉
