### ISSUE TITLE
New version hard to install

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#17]
I am running 3.0.1.0 and when I use the Check for Update button it says I have the latest version even though 3.0.2.0 is available. When I look at the package availability in winget all I see are versions 1.3.0.1 and 2.1.0.0. So the only way to install the new version is to download the rar file and extract the executable into the correct directory.

**Comment by ghost1372** [comment]
I have not yet submited version 3 on Winget So yes, as you said, the only way is to download the RAR version
This seems to be a bug. Thanks for the report

**Comment by tardis4500** [comment]
There isn't even a rar for 3.1.2.0.

**Comment by ghost1372** [comment]
@tardis4500  last version is 3.0.2.0🤨

**Comment by ghost1372** [comment]
Fixed in https://github.com/HandyOrg/HandyWinGet/commit/f7dddd6832b0d5b2fd1430021a5c5bad54a341ce

**Comment by ghost1372** [comment]
@tardis4500  new version 3.2.0.0 is [available](https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.2.0.0)  I will update the Winget version soon
