### ISSUE TITLE
Crashes when I try to search

### ISSUE THREAD

**Issue by joroad** [HandyOrg/HandyWinGet#18]
When I click on the search bar and type in one character, the application freezes, then the application closes. I included a video demonstrating the bug. 

https://user-images.githubusercontent.com/43655781/113361053-0dcdf900-9319-11eb-8e21-85e338ad99d0.mp4

**Comment by JohnLGalt** [comment]
Odd.  Not happening here.  Has this always happened, or did it just start happening recently?

**Comment by ghost1372** [comment]
Thanks for the report. Are you using the latest version 3.0.2.0? I can see in the video that the rows have no text So it makes sense for the app to run into problems when searching.
First we have to solve the problem of empty rows. After that, the search problem will be solved.
