### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by JohnLGalt** [HandyOrg/HandyWinGet#22]
1)  When clicking the 3x3 square icons at top left, it selects all items in view - as expected.  But if I want to reverse the process, I can't - I have to manually deselect everything (or restart client).  Can this be changed to both select *and* deselect all, depending upon the last action used (IOW:  If not used, it becomes select all, if already used once to select all, it becomes deselect all, and if it was last used to deselect all, it becomes normal select all again)?

2)  Is there a reason the drop down boxes for Architecture as as wide as they currently show?  If not, can it be reduced?

3)  Can column widths be made persistent?  After I adjust them to where I want them, upon app restart they are back to 'default' settings.

**Comment by ghost1372** [comment]
In the next version, I will implement 1 and 2 but I do not have an opinion about the third option at the moment, if it is possible, I will definitely consider it

**Comment by ghost1372** [comment]
Hi I implemented 1 and 2
https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.3.0

![Animation](https://user-images.githubusercontent.com/9213496/116401606-adab7380-a840-11eb-8f78-c73c78529331.gif)

**Comment by ghost1372** [comment]
Save and Restore DataGrid Columns width, Added in version 3.4.0
