### ISSUE TITLE
Installed repositories showing apps not actually installed

### ISSUE THREAD

**Issue by JohnLGalt** [HandyOrg/HandyWinGet#23]
HI,

good work on 3.3.0.0.  I have a feeling this bug report is not related to HWG directly, but to WinGet / parsing of metadata / some other issue.

Using 3.3.0.0, and selecting Show only installed button at bottom right, I get a lot of apps listed that are actually not installed.

- Concept2 - Utility (if I try to uninstall it the uninstaller for my NetGear ProSafe mgmt utility comes up.  Maybe it makes use of the Concept2 utility?
- dnGrep   dnGrep (never installed it, uninstaller says unable to uninstall, even when running HWG as admin)
- gnome - Dia and gnome gedit  (never installed either one, uninstaller says unable to uninstall, even when running HWG as admin)
- GoCD - Server (uninstaller tries to uninstall my RivaTuner Statistics Server that comes with MSI Afterburner)
- Golang - Go (uninstaller attempts to uninstall Google Drive FileStream app)
- Johannes - Schindelin Git (never installed it, uninstaller says unable to uninstall, even when running HWG as admin)
- LINE Corporation - LINE (never installed it, uninstaller says unable to uninstall, even when running HWG as admin)
- Nicholas H Tollervey - Mu (never installed, Uninstall brings up a generic Windows uninstaller dialog box so I have no idea what actual app it is trying to uninstall)
- richasy - Bili (never installed it, uninstaller says unable to uninstall, even when running HWG as admin)
- Tencent - TIM (never installed it, uninstaller says unable to uninstall, even when running HWG as admin)
- WPEngine, Inc - Local (never installed, Uninstall brings up a generic Windows uninstaller dialog box so I have no idea what actual app it is trying to uninstall)

I suspect, from the NetGear and RivaTuner uninstall routines, that what is actually happening is that there are either false positives in the scan for installed items, or else some of these items are a part of other actual installations versus being installed manually / on their own.

If I can provide logs, or anything like that, please let me know.

Also, a couple of these do not show up in 3.2.2.0:

dnGrep, GoLang, Git, Billi, and TIM do not show as installed in 3.2.2.0

Is it possible to use a program UUID instead, or do most of these not have an associated UUID to hunt down?

**Comment by ghost1372** [comment]
@JohnLGalt  thank you for your feedback
for uninstalling package, Each program installed in the registry has a uninstall string, but, some of them do not have this string so hwg is Unable to uninstall package
also it seems that, uninstall string is not seted correctly for items
 I will try to check soon

**Comment by JohnLGalt** [comment]
Not surprising.  Not every developer is ... savvy.  Even if their applications are awesome.  Lol.

**Comment by RMITBLOG** [comment]
> @JohnLGalt thank you for your feedback
> for uninstalling package, Each program installed in the registry has a uninstall string, but, some of them do not have this string so hwg is Unable to uninstall package
> also it seems that, uninstall string is not seted correctly for items
> I will try to check soon

@ghost1372  I found the same issue. I will check with a few other apps but cannot get 7zip to show.

**Comment by RMITBLOG** [comment]
@ghost1372  To confirm I tried Link shell Extention. this shows to be working in your gif. However its not showing as installed like all other apps.

**Comment by RMITBLOG** [comment]
> @ghost1372 To confirm I tried Link shell Extention. this shows to be working in your gif. However its not showing as installed like all other apps.

It turns out there is no issue. User error: the show installed package path was not set

![image](https://user-images.githubusercontent.com/48697709/120049920-78e33580-c013-11eb-9c65-d8d619fbfa83.png)

😀😀

**Comment by JohnLGalt** [comment]
> 
> 
> Not surprising. Not every developer is ... savvy. Even if their applications are awesome. Lol.

I just realized, in re-reading what I wrote - I was *NOT* referring to *you*, @ghost1372 - I was referring to ***other*** developers.

I'm so sorry for the implied insult, truly!

**Comment by ghost1372** [comment]
I close this issue And I will follow it [in this issue](https://github.com/HandyOrg/HandyWinGet/issues/21)
