### ISSUE TITLE
Not reporting current versions of software

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#24]
When I run a command line "winget search pgadmin4" it shows the latest version as 5.2 but HandyWinGet show the latest as 5.1 and doesn't show 5.2 at all in the drop-down.

**Comment by JohnLGalt** [comment]
I asked the same thing - it is based upon the manifests that Microsoft makes available to the winget CLI utility, and so the winget only has access to the latest software as Microsoft makes them available.

**Comment by tardis4500** [comment]
But in this case the winget CLI shows a new version than this GUI.

**Comment by JohnLGalt** [comment]
Then use the refresh Pacakges button near the bottom right.  I just tried it, it does show 5.1 initially, but after refresh it shows 5.2

**Comment by tardis4500** [comment]
I see. It's somewhat counter-intuitive that it doesn't refresh automatically at startup. There should probably be an option for that.

**Comment by JohnLGalt** [comment]
I can get on board with that.  I suspect that it might be a case of not spamming the servers from people (like me) who tend to start and stop the app more than once a day though ;P

At any rate, @ghost1372 is really good at both responding as well as continuing development on this app, so maybe it might could be added as an option (a user-configurable option would be best, so those of us who want it can have it and those who don't can leave it off).

See the previous I started to see just how far down the rabbit hole we went lol...

**Comment by ghost1372** [comment]
@tardis4500  @JohnLGalt 
I added an option to control this situation 😁
also 2 other options were also added 
I have to mention that the pages are not cached at the moment and after navigating the page, all the pages are re-created
I'm working on this
![Untitled](https://user-images.githubusercontent.com/9213496/117698839-65de0200-b1d9-11eb-9d6b-3ef32f103232.png)

https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.4.1

**Comment by JohnLGalt** [comment]
> 
> 
> I can get on board with that. I suspect that it might be a case of not spamming the servers from people (like me) who tend to start and stop the app more than once a day though ;P
> 
> At any rate, @ghost1372 is really good at both responding as well as continuing development on this app, so maybe it might could be added as an option (a user-configurable option would be best, so those of us who want it can have it and those who don't can leave it off).
> 
> See the previous issue I started to see just how far down the rabbit hole we went lol...

Told ya he's fast 🥇
