### ISSUE TITLE
Wrong version in package

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#28]
The 3.4.1 zip file has 3.4.0 in it so after install it still says a newer version is available.

**Comment by JohnLGalt** [comment]
I noticed this as well, but forgot to report.

so, "Confirmed" here as well.

**Comment by ghost1372** [comment]
When I released version 3.4.0, I realized that there was an important bug, so I just fixed bug and forgot to increase the version number in the program😁. The release process is a bit time consuming and I have to zip and upload the output file So I just changed the version number in GitHub At that time I forgot that this problem occurs (sorry😁) To check the new version, the program compares the GitHub tag with the version number of its exe file

Now I changed the GitHub tag number to 3.4.0 and we should not have any more wrong reports
