### ISSUE TITLE
Consider adding .editorconfig for consistency

### ISSUE THREAD

**Issue by Elepover** [HandyOrg/HandyWinGet#29]
First of all, HWG is awesome and a huge shout out for your hard work!

While I was reading its code, I found that this project is using `PascalCase` for argument names, rather than the default `camelCase` naming scheme (at least in Visual Studio and Rider’s), this may introduce inconsistency while someone’s trying to contribute new code to this repo.

I don’t personally consider `PascalCase` to be good for variable names since it may cause you to mix variables and class/type names but it’s really down to **personal preferences**.

Adding a `.editorconfig` file can explicitly set the naming scheme preference for the project, make IDE automatic formatting work better and save time for developers, and I think that you might be interested in it. It will also make Rider complain less with its more strict syntax checking system.

Visual Studio also provided a template, you can directly create one in the Add File menu.

**Comment by ghost1372** [comment]
Thank you, I will definitely consider it

**Comment by ghost1372** [comment]
EditorConfig Added in https://github.com/HandyOrg/HandyWinGet/commit/d8f500f55f8dad0ffadb48d5db0ef8c9f05ed5a4
