### ISSUE TITLE
Update Dialog with asian OK / Cancel buttons

### ISSUE THREAD

**Issue by callmeconnor** [HandyOrg/HandyWinGet#30]
Looks like something is not correct here:
![image](https://user-images.githubusercontent.com/75158410/119937874-cb790f00-bf8b-11eb-9c3e-0aaf79c26f16.png)

Repeatability: 
General -> Check for Update -> (See screenshot)

Environment:
Windows 10 Pro, German locale

**Comment by ghost1372** [comment]
Thank you for report
I will fix in the next version
