### ISSUE TITLE
No shortcuts installed in Start Menu

### ISSUE THREAD

**Issue by Kaylakaze** [HandyOrg/HandyWinGet#31]
I installed via WinGet but no Start Menu items were created, using search for "Handy" returns nothing, and it's not like the installer told me where it was installing the executable. How do I run this thing?

**Comment by ghost1372** [comment]
Hi @Kaylakaze 
After installation, the program shortcut must be created on the desktop
However, the installation path specified in Advanced Installer is: **[AppDataFolder][Manufacturer]\[ProductName]** => **C:\Users\AppData\Roaming\HandyOrg\HandyWinget**
You may also find the program in this path 
**C:\Users\Mahdi\AppData\Local\Temp\.net\HandyWinget**
I'm planning to rewrite the program by UWP, Therefore, this type of problem will not occur again.

**Comment by Kaylakaze** [comment]
Thanks. I don't use the desktop so of course, I didn't see it. Thanks for the install location.

**Comment by Nyaacinth** [comment]
For now there's still nothing installed in start menu, will this feature be added or there's something going wrong on my device?

**Comment by JohnLGalt** [comment]
IT hasn't changed. @ghost1372 has been pretty busy, and the last public release was barely 2 weeks after this post was first made.  https://github.com/HandyOrg/HandyWinGet/releases

**Comment by Nyaacinth** [comment]
> IT hasn't changed. @ghost1372 has been pretty busy, and the last public release was barely 2 weeks after this post was first made. https://github.com/HandyOrg/HandyWinGet/releases

Got it. Thanks for response.
