### ISSUE TITLE
Installed version doesn't match what winget cli reports

### ISSUE THREAD

**Issue by tardis4500** [HandyOrg/HandyWinGet#32]
I have WinMerge installed and when I do a "winget list WinMerge" it reports that 2.16.12.0 is installed. But the GUI reports that 2.16.6 is installed. This is true even though I have selected the "Winget-cli Method" for the Show Installed Package option.

**Comment by ghost1372** [comment]
duplicate https://github.com/HandyOrg/HandyWinGet/issues/21
