### ISSUE TITLE
Language: Theme -  AccentColor - Buttons

### ISSUE THREAD

**Issue by timon89** [HandyOrg/HandyWinGet#34]
Hi there
The Buttons on the "Accent Color" Popup are not in english.

Thx!

![image](https://user-images.githubusercontent.com/59319696/120922950-5e245700-c6cc-11eb-93e0-3fc26ae6a1c8.png)

**Comment by ghost1372** [comment]
same as https://github.com/HandyOrg/HandyWinGet/issues/30
