### ISSUE TITLE
Cleaner Packages Tab

### ISSUE THREAD

**Issue by hl2guide** [HandyOrg/HandyWinGet#39]
Please fix this tab to only show packages that have a **Package Name**.

Currently theres blank ones until index number 12.

**Comment by ghost1372** [comment]
can you provide a screenshot?

**Comment by hl2guide** [comment]
![example](https://user-images.githubusercontent.com/17044982/125193845-f399a480-e291-11eb-9cc4-9d3149eb8ada.png)

**Comment by ghost1372** [comment]
You are using old version, please use version 4 beta
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1
This issue has been fixed
