### ISSUE TITLE
Slow to populate packages (no pre-caching)

### ISSUE THREAD

**Issue by nascentt** [HandyOrg/HandyWinGet#45]
Takes a long time to populate packages tab, my first run seemed to get stuck and needed a close/reopen after a few minutes, subsequent opens take about 30 seconds each time.

![handywinget- slow start](https://user-images.githubusercontent.com/1145722/129870048-afae2469-c82a-4f9d-aa16-d364c9ea3dd9.png)

This is even with "show installed package" off

**Comment by ghost1372** [comment]
please use version 4.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1

**Comment by JohnLGalt** [comment]
Really use it - it grabs and parses the packages in less than 3 seconds on my machine.  Seriously a wondrous speed increase.
