### ISSUE TITLE
Blank packages

### ISSUE THREAD

**Issue by nascentt** [HandyOrg/HandyWinGet#46]
For some reason, some packages are blank rows. (see #1)

![handywinget - blank](https://user-images.githubusercontent.com/1145722/129870158-0aba4205-7724-464f-a954-2da0cddd4b98.png)

**Comment by ghost1372** [comment]
this issue fixed in version 4.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1
