### ISSUE TITLE
visible environment variables

### ISSUE THREAD

**Issue by nascentt** [HandyOrg/HandyWinGet#47]
![handywinget - envauthor](https://user-images.githubusercontent.com/1145722/129870303-09157752-5679-49ec-9a7d-fcfd57cdf366.png)

see column #3 "${env:THE_AUTHOR}"

**Comment by ghost1372** [comment]
this issue fixed in version 4.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1
