### ISSUE TITLE
Show Only Installed ignored

### ISSUE THREAD

**Issue by nascentt** [HandyOrg/HandyWinGet#48]
The "Show Only Installed" checkbox at the bottom right of the package window is ignored by default.

With it left selected, if I navigate away from the packages tab then back to packages, it'll load all packages, even those not installed.  I have to then unselect "Show Only Installed" and re-select it to only see installed packages.

This is the case using either the internal method or the winget cli method for internal packages

**Comment by ghost1372** [comment]
try version 4.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1
