### ISSUE TITLE
Upgrade support: No upgrade button / Packages tab shows available version but not installed version

### ISSUE THREAD

**Issue by nascentt** [HandyOrg/HandyWinGet#49]
Packages tab shows installed version but not installed version for installed packages, it also seems only shows an install button but not an upgrade button for already installed packages
![handyget-upgrade](https://user-images.githubusercontent.com/1145722/129871823-6570cf96-4f58-406f-b0fe-51ecf2a43a75.png)

**Comment by ghost1372** [comment]
try version 4.0
https://github.com/HandyOrg/HandyWinGet/releases/tag/v4.0.0-beta.1
