### ISSUE TITLE
View installed packages

### ISSUE THREAD

**Issue by rp1231** [HandyOrg/HandyWinGet#6]
Would it be possible to view the packages installed through winget.
Something like what exists in the chocolatey gui.

Thanks.

**Comment by ghost1372** [comment]
@rp1231  Yes from settings you can enable it
after that An icon is displayed next to the installed applications in the list

**Comment by rp1231** [comment]
The icon doesn't seem to be appearing for me.

**Comment by rp1231** [comment]
The icon is showing up for another app.
But not for ccleaner.
But I just saw that you have mentioned in the settings that not all programs will be decected.
Thanks

**Comment by rp1231** [comment]
An option for sorting the detected apps would be great if possible!
Exellent work so far.
Thanks

**Comment by ghost1372** [comment]
@rp1231  I identify the installed programs by checking the registry keys So some software may not have a registry key or the program may not find the key.

It seems that Microsoft developed a standard way to identify installed applications also a way for updating applications.
I plan to rebuild this program soon with better features
Thank you for reminding me

**Comment by rp1231** [comment]
Looking forward to the new version.

**Comment by ghost1372** [comment]
Hi @rp1231 
I created the new version It is also possible to sort by clicking on the column name😁
The ability to view installed applications and Upgrade them is not yet enabled I am waiting for this features (https://github.com/microsoft/winget-cli/issues/119 https://github.com/microsoft/winget-cli/issues/120) to be taken out of the [experimental](https://github.com/microsoft/winget-cli/releases/tag/v0.2.2941-preview) mode then I can add it in the program

[Take a test](https://github.com/HandyOrg/HandyWinGet-GUI/releases/tag/v2.0.0-beta)

**Comment by rp1231** [comment]
Hey, looks so much cleaner!
Also love that the program versions are now grouped in a drop down menu.

**Comment by ghost1372** [comment]
Done😁
https://github.com/HandyOrg/HandyWinGet/releases/tag/v2.0.0.0

**Comment by rp1231** [comment]
Woo hoo!
